### ISSUE TITLE
Developer notes

### ISSUE THREAD

**Issue by logbaseaofn** [logbaseaofn/bhbh-react#173]
Now that I have a proper way to display developer only stuff, I'd like to add a dev notes things. Dev notes will be in their own collection, and if you're a dev, then each page will query for dev notes. There can be a + button to add a note, and each note can be deleted. I'd like a (x) number somewhere that indicated the dev notes, then they can be popped up in a modal. In short:

- No dev notes: + add dev note
- Is dev notes: (x) icon for x dev notes
- When the icon is clicked a modal pops up with all the dev notes and the ability to add more and delete current ones.
- I'd like the text to be stored as markdown or something so I can actually use it.
- I'm not sure about the ability to edit it... that seams like a bit much.. but maybe it'd be important for checklists?

**Comment by logbaseaofn** [comment]
# TODO
- [ ] Button in dev toolbar
- [ ] Edit/add dev note modal
- [ ] Add dev notes to firestore
- [ ] Can edit a dev note
- [ ] Can delete a dev note
- [ ] Badge showing how many dev notes
- [ ] Dev notes have text content
- [ ] Dev notes have a classifier (TODO, HIST, QUESTION, etc). Need to decide what these are yet.

**Comment by logbaseaofn** [comment]
Should TODO items be deleted when they're done, or marked as resolved? I'd like these to get printed in the developers cut of the book... so maybe TODO items should just be deleted.

**Comment by logbaseaofn** [comment]
How do I go about ordering these things? Should they have an order to them?

**Comment by logbaseaofn** [comment]
Order by time created/updated

**Comment by logbaseaofn** [comment]
No resolving, just delete todos afterwards. If they're interesting enough to stay, they can be updated and made into info notes.

**Comment by logbaseaofn** [comment]
- [ ] Add notes to home page
- [ ] Add notes to boulders
- [ ] Add notes to problems
